### PR TITLE
Update OpenFlexTyper_CondaEnv.yml

### PR DESCRIPTION
**Pull request by kounkou**
Hi there,

This will add git-lfs to the repo clones

Regards

### CODE REVIEW

**Comment by kounkou** [comment]
To use git-lfs, please refer to the documentation : 
https://github.com/git-lfs/git-lfs/wiki/Tutorial

**Comment by Phillip-a-richmond** [comment]
Have you tested this on Sockeye?

**Comment by kounkou** [comment]
of course :sunglasses:

**Comment by Phillip-a-richmond** [comment]
Can we merge this too already? Lets gooooo

**Pull request merged**
